; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

monitor_speed = 115200

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=3

lib_extra_dirs = third_party


lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit GFX Library @ ^1.11.11
    sensirion/Sensirion I2C SHT4x @ ^1.1.0
    sensirion/Sensirion Core @ ^0.7.1
    https://github.com/boschsensortec/BMP5_SensorAPI.git
    sensirion/Sensirion I2C SCD4x @ ^0.4.0
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
    https://github.com/Sensirion/arduino-i2c-sgp41.git
    sensirion/Sensirion Gas Index Algorithm @ ^3.2.3
    mathieucarbou/ESPAsyncWebServer @ ^3.3.23
    mathieucarbou/AsyncTCP @ ^3.2.14
    bblanchon/ArduinoJson @ ^7.1.0
    mikalhart/TinyGPSPlus @ ^1.1.0
[env:native]
platform = native
build_flags = -std=c++11
lib_deps =
test_build_src = yes
build_src_filter = +<utils/pulse_analyzer.cpp> -<main.cpp> -<services/> -<drivers/>

[env:bmp585_test]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=3
lib_deps =
    https://github.com/boschsensortec/BMP5_SensorAPI.git
build_src_filter = +<../scratch_test_bmp585.cpp> -<*>

[env:bmp581_test]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=3
lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit GFX Library @ ^1.11.11
    sensirion/Sensirion I2C SHT4x @ ^1.1.0
    sensirion/Sensirion Core @ ^0.7.1
    https://github.com/boschsensortec/BMP5_SensorAPI.git
    sensirion/Sensirion I2C SCD4x @ ^0.4.0
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
    https://github.com/Sensirion/arduino-i2c-sgp41.git
    sensirion/Sensirion Gas Index Algorithm @ ^3.2.3
build_src_filter = +<*> -<main.cpp> +<../scratch_test_bmp581.cpp>

[env:scd41_test]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=3
lib_deps =
    sensirion/Sensirion I2C SCD4x @ ^0.4.0
    sensirion/Sensirion Core @ ^0.7.1
build_src_filter = +<../scratch_test_scd41.cpp> -<*>

[env:sgp41_test]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=3
lib_deps =
    https://github.com/Sensirion/arduino-i2c-sgp41.git
    sensirion/Sensirion Gas Index Algorithm @ ^3.2.3
    sensirion/Sensirion Core @ ^0.7.1
build_src_filter = +<../scratch_test_sgp41.cpp> -<*>

[env:sd_test]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=3
lib_deps =
build_src_filter = +<../scratch_test_sd.cpp> -<*>

[env:fram_test]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=3
lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit GFX Library @ ^1.11.11
    sensirion/Sensirion I2C SHT4x @ ^1.1.0
    sensirion/Sensirion Core @ ^0.7.1
    https://github.com/boschsensortec/BMP5_SensorAPI.git
    sensirion/Sensirion I2C SCD4x @ ^0.4.0
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
    https://github.com/Sensirion/arduino-i2c-sgp41.git
    sensirion/Sensirion Gas Index Algorithm @ ^3.2.3
build_src_filter = +<*> -<main.cpp> +<../scratch_test_fram.cpp>
